/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoversRouteImport } from './routes/covers'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as OrganizeRouteImport } from './routes/organize'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as WaitlistRouteImport } from './routes/waitlist'
import { Route as AlbumIdRouteImport } from './routes/album.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoversRoute = CoversRouteImport.update({
  id: '/covers',
  path: '/covers',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizeRoute = OrganizeRouteImport.update({
  id: '/organize',
  path: '/organize',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitlistRoute = WaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumIdRoute = AlbumIdRouteImport.update({
  id: '/album/$id',
  path: '/album/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/covers': typeof CoversRoute
  '/library': typeof LibraryRoute
  '/organize': typeof OrganizeRoute
  '/privacy': typeof PrivacyRoute
  '/waitlist': typeof WaitlistRoute
  '/album/$id': typeof AlbumIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/covers': typeof CoversRoute
  '/library': typeof LibraryRoute
  '/organize': typeof OrganizeRoute
  '/privacy': typeof PrivacyRoute
  '/waitlist': typeof WaitlistRoute
  '/album/$id': typeof AlbumIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/covers': typeof CoversRoute
  '/library': typeof LibraryRoute
  '/organize': typeof OrganizeRoute
  '/privacy': typeof PrivacyRoute
  '/waitlist': typeof WaitlistRoute
  '/album/$id': typeof AlbumIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/covers'
    | '/library'
    | '/organize'
    | '/privacy'
    | '/waitlist'
    | '/album/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/covers'
    | '/library'
    | '/organize'
    | '/privacy'
    | '/waitlist'
    | '/album/$id'
  id:
    | '__root__'
    | '/'
    | '/covers'
    | '/library'
    | '/organize'
    | '/privacy'
    | '/waitlist'
    | '/album/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoversRoute: typeof CoversRoute
  LibraryRoute: typeof LibraryRoute
  OrganizeRoute: typeof OrganizeRoute
  PrivacyRoute: typeof PrivacyRoute
  WaitlistRoute: typeof WaitlistRoute
  AlbumIdRoute: typeof AlbumIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/covers': {
      id: '/covers'
      path: '/covers'
      fullPath: '/covers'
      preLoaderRoute: typeof CoversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organize': {
      id: '/organize'
      path: '/organize'
      fullPath: '/organize'
      preLoaderRoute: typeof OrganizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waitlist': {
      id: '/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof WaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album/$id': {
      id: '/album/$id'
      path: '/album/$id'
      fullPath: '/album/$id'
      preLoaderRoute: typeof AlbumIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoversRoute: CoversRoute,
  LibraryRoute: LibraryRoute,
  OrganizeRoute: OrganizeRoute,
  PrivacyRoute: PrivacyRoute,
  WaitlistRoute: WaitlistRoute,
  AlbumIdRoute: AlbumIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
